### PR TITLE
Require and run Quill.js outside angular

### PR DESCRIPTION
**Pull request by kamilchlebek**
Resolves: #610

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
nice! thanks man.

**Comment by kamilchlebek** [comment]
That was fast :rocket: :smiley:

**Comment by KillerCodeMonkey** [comment]
*thats what she said 😁

new release is coming in a view minutes

**Comment by kamilchlebek** [comment]
I'm still looking for some performance improvements. I'll keep you posted

**Pull request merged**
