### PR TITLE
feat(EditorComponent): dynamic editor css classes

### LINKED ISSUE #505: Option to add classes as an input to be added to the element
I would like to be able to pass a space-separated list of classes (much like the typical class input on html directives) to the quill-editor, is there a reason this is not supported as of now? I would glady write the code and open a PR if this is something that would be merged in?

### PR DESCRIPTION
**Pull request by yharaskrik**
Adds an input to include CSS classes that will be added to the editor element the same way that styles are handled. 

Resolves #505

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
@yharaskrik Looks nice i guess. But could you extend the readme with that new config property?

**Comment by yharaskrik** [comment]
Ah the one thing I forgot! I will do that today! Thanks!

**Comment by KillerCodeMonkey** [comment]
no probs. i have to thank you :)

**Comment by yharaskrik** [comment]
All done! Added `classes` to the Config section of the documentation

**Comment by KillerCodeMonkey** [comment]
Nice i will Check and merge this later or tomorrow morning.
And will Release a new Release


Jay Bell <notifications@github.com> schrieb am Do., 5. Sep. 2019, 16:56:

**Comment by yharaskrik** [comment]
Thank you very much! I look forward to it.

**Pull request merged**
