### PR TITLE
Update package.json

### LINKED ISSUE #175: Why is node locked to version 8?
```
error ngx-quill@3.0.0: The engine "node" is incompatible with this module. Expected version "8".
error An unexpected error occurred: "Found incompatible module".
```

### PR DESCRIPTION
**Pull request by princemaple**
close #175

### CODE REVIEW

**Comment by princemaple** [comment]
Your repo master passed build on node 6.9.2
You see why that engine restriction is not necessary?

**Comment by KillerCodeMonkey** [comment]
yeah, but this is more something for myself for development. Sure the tests may pass on lower version.

But this is the version i can garantuee that ngx-quill works. 
I have a fulltime job and a house and hobbies. So i do not want more useless issues like "oh now there is node xx, and it is not working" or "why it is not working with with node 0.10".

So maybe i find a solution to kick it out for the published release

**Comment by princemaple** [comment]
Makes sense. All I wanted was to make it work on Node 8+. Please be sure to make a release!

**Comment by KillerCodeMonkey** [comment]
are you familar with angular universal, because i changed stuff to avoid issues with SSR in the dev branch. and i need a victim for testing :)

**Comment by princemaple** [comment]
Sorry no I'm not. I don't use Node as my backend. Angular starting from the client side is fast enough for my use cases. I'm sure you can get some help if you ask on [Reddit](https://www.reddit.com/r/angular/) or somewhere else.

**Comment by KillerCodeMonkey** [comment]
or i simply throw the stuff in the next hotfix release and let it rock and roll :)

**Comment by princemaple** [comment]
🤘

**Comment by princemaple** [comment]
RDD: release driven debugging

**Pull request merged**
