### PR TITLE
feat: implement `ngx-quill/config` package for providing a global config

### PR DESCRIPTION
**Pull request by arturovt**
I've created a subpackage `ngx-quill/config`. It exports interfaces and `QUILL_CONFIG_TOKEN`. This adds an ability to provide a global config on the `AppModule` level w/o importing `QuillModule` (and its components) into the root bundle.

The `ngx-quill` re-exports everything from `ngx-quill/config` so consumers won't need to do any changes.

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
But then i would expect that both modules are living under ngx-quill/src, since i will only bundle this for production.
They are not two independent projects, so just move the sources to ngx-quill/src and merge the public_api. 

The folder and file structure makes no sense to me is quite confusing.

**Comment by arturovt** [comment]
The folder structure follows the ng-packagr guide: https://github.com/ng-packagr/ng-packagr/blob/main/docs/secondary-entrypoints.md

I don't understand what this means:

> But then i would expect that both modules are living under ngx-quill/src, since i will only bundle this for production.
They are not two independent projects, so just move the sources to ngx-quill/src and merge the public_api.

**Comment by KillerCodeMonkey** [comment]
luls. that they decided to go this way with directory structure. i find it more then confusing, that you put depending modules not under "src" folder of the primary module.

**Comment by KillerCodeMonkey** [comment]
yep i know. i am just confused by the ng-packagr way of doing those things. never used to create a "sub"-bundle. but it is strange to explain why it lives beside the src-dir of the project/package, but is then part of it as its own module. So i would expect that there would be some sort of special dir structure or config under "ngx-quill/src"... but wayne.

**Pull request merged**
