### PR TITLE
default-empty-value setter | issue 1257

### PR DESCRIPTION
**Pull request by Y4Rick**

### CODE REVIEW

**Review by KillerCodeMonkey — CHANGES_REQUESTED** [review]

**Comment by KillerCodeMonkey** [comment]
@Y4Rick any updates?

**Comment by Y4Rick** [comment]
stell in progress.
On vacation up to 7.06

**Comment by KillerCodeMonkey** [comment]
any update?

**Comment by Y4Rick** [comment]
updated

**Review by KillerCodeMonkey — APPROVED** [review]

**Pull request merged**
