### PR TITLE
refactor(QuillEditor): normalize classList

### PR DESCRIPTION
**Pull request by yharaskrik**
@KillerCodeMonkey my QA developer noticed a small bug where when the classes input had extra white space in it renderer would error trying to add an invalid class. This PR should fix that.

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
please rebase your project repo with the latest changes from here :)

**Comment by yharaskrik** [comment]
Oops thought I did!  I'll get that done this morning.

**Comment by KillerCodeMonkey** [comment]
no probs :). Thanks

Do you work as a freelancer?

**Comment by yharaskrik** [comment]
No I do not, I run a tech company in Canada!

**Comment by KillerCodeMonkey** [comment]
ui, a friend and i will start a small business in germany as full remote developers at the beginning of 2020.
Maybe we can build something together in the future :D.

**Comment by yharaskrik** [comment]
Awesome congrats, will you be doing angular development?

Yes maybe we can! I would like that.

**Comment by KillerCodeMonkey** [comment]
Thanks :).

Not only. We are open for angular, react, vuejs and have quite good experiences with native javascript :).

But we are working with angular since v1 and ionic since the first alpha :D.

And we are doing backend development with nodejs, php, python (hopefully elixir in the future).

**Comment by yharaskrik** [comment]
Wow that is a lot of different technologies! I only know a small subset of those.

Branch has been rebased as well now.

**Comment by KillerCodeMonkey** [comment]
Thanks Mate. I will merge this later or tomorrow :)

Jay Bell <notifications@github.com> schrieb am Mo., 9. Sep. 2019, 18:28:

**Comment by yharaskrik** [comment]
Awesome sounds good thank you!

**Comment by KillerCodeMonkey** [comment]
its merged and i released a new "hotfix" version for that refactoring.

**Comment by yharaskrik** [comment]
You are welcome! Expect them to keep coming!

**Pull request merged**
