### PR TITLE
added 'format' input to support both html and delta json natively

### PR DESCRIPTION
**Pull request by Syam**

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
Her thanks, but Check latest Version of ngx-quill i commented in the issue,
that i added the Option to handle Format Object,  Text and html

Jean Christophe Huwette <notifications@github.com> schrieb am Fr., 6. Juli
2018, 21:11:

**Comment by Syam** [comment]
Yes i just saw your commits while pull requesting :)

I juste test your commit, it does not work for me, because it miss a json string format.
I will work on a PR based on your last updates.

Regards,

**Comment by KillerCodeMonkey** [comment]
Why json string? Simply Run json.parse before setting Your Model?

Jean Christophe Huwette <notifications@github.com> schrieb am Fr., 6. Juli
2018, 21:31:

**Comment by Syam** [comment]
Unfortunately, not the best way in a reactive form

Input components are supposed to update models directly without any transformer.
Solution is to write a component wrap and override writer/reader accessors. Quite dirty :(

I need a `json.stringify()` to send string data to my API (not a full structured object) and `json.parse()` on reading the API data.

Your last commits is really great, the `format` values should be `html | object | text | json` to cover all possible needs.

**Comment by KillerCodeMonkey** [comment]
Okay feel free to extend it

Jean Christophe Huwette <notifications@github.com> schrieb am Fr., 6. Juli
2018, 22:15:

**Comment by Syam** [comment]
Thanks !

**Comment by KillerCodeMonkey** [comment]
But maybe we found a better Name than json.. Maybe objectString.

Jean Christophe Huwette <notifications@github.com> schrieb am Fr., 6. Juli
2018, 22:17:

**Comment by Syam** [comment]
JSON is a serialized result of an object, i can't find better name

Regarding the Quill documentation, they also speak about JSON:
```
Deltas are a simple, yet expressive format that can be used to describe Quill’s contents and changes. The format is essentially JSON, and is human readable, yet easily parsible by machines. 
```
https://quilljs.com/docs/delta/

**Comment by KillerCodeMonkey** [comment]
Okay, i used 'object' when You Pass the Operations Array or Object to the
Model.

Jean Christophe Huwette <notifications@github.com> schrieb am Sa., 7. Juli
2018, 00:02:

**Pull request closed without merging**
