### PR TITLE
perf: unpatch `document.addEventListener` when the `quill` is imported

### PR DESCRIPTION
**Pull request by arturovt**
See code comments, that won't bring any breaking change but will only improve the app performance since Quill added event listeners won't cause many change detections to run.

### Before

before

### After

after

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
i have a little problem with it, because you may overwrite the whole document.addEventListener... keep in mind you could run the angular app only as part of a website. So i do not know, if this is a good idea

**Comment by arturovt** [comment]
Hey, not sure what you mean by:

> you may overwrite the whole document.addEventListener.

We do overwrite it with a native API before the Quill is imported and restore back to the original value after the Quill is imported.

I can try another approach of wrapping the import with `runOutsideAngular` if the current approach doesn't suit you.

**Comment by KillerCodeMonkey** [comment]
@arturovt could you please check, if it possible to inject the document like `@Inject(DOCUMENT) doc: any`?

**Comment by arturovt** [comment]
Sure, it's possible.

**Comment by arturovt** [comment]
There's another approach:
```ts
const quillImport = await this.ngZone.runOutsideAngular(() => import('quill'))
```

But this is more problematic since the task will be spawned in the root zone inside the testing environment and `fixture.whenStable()` wouldn't wait for it.

**Comment by KillerCodeMonkey** [comment]
One question: why using `injector.get` instead of `@Inject` directly?

**Comment by arturovt** [comment]
Because of the `Metadata collected contains an error that will be reported at runtime: Could not resolve type Document.`. Don't wanna add the `// @dynamic` comment since it breaks metadata collection for the class or use the `any` type.

**Comment by KillerCodeMonkey** [comment]
@arturovt maybe we can then change the other injections of Document in that way?

**Comment by KillerCodeMonkey** [comment]
@arturovt maybe we can then change the other injections of Document in that way?

**Comment by arturovt** [comment]
Sure.

**Pull request merged**
